name: PistonEntityFixer
version: ${project.version}
api-version: 1.13
main: net.pistonmaster.pistonentityfixer.PistonEntityFixer
authors: [ AlexProgrammerDE ]
description: Lists and kills entities as you wish.
permissions:
  pistonentityfixer.fix:
    description: Plugin main permission.
commands:
  fixentities:
    description: Plugin main command.
    permission: pistonentityfixer.fix
  getentitybyid:
    description: Get entities by id.
    permission: pistonentityfixer.fix
  tameinfo:
    description: Info over tameables
    permission: pistonentityfixer.fix
  topentities:
    description: Info over top entities
    permission: pistonentityfixer.fix
  topplace:
    description: Info over top places
    permission: pistonentityfixer.fix