name: PistonEntityFixer
version: ${project.version}
api-version: 1.13
main: net.pistonmaster.pistonentityfixer.PistonEntityFixer
authors: [ AlexProgrammerDE ]
description: Lists and kills entities as you wish.
permissions:
  pistonentityfixer.fix:
    description: Plugin main permission.
commands:
  fixentities:
    description: Kill and list entities by type.
    permission: pistonentityfixer.fix
  getentitybyid:
    description: Get entities by id.
    permission: pistonentityfixer.fix
  tameinfo:
    description: Info about tameables.
    permission: pistonentityfixer.fix
  topentities:
    description: List of top entities.
    permission: pistonentityfixer.fix
  topplace:
    description: List of top places of entities.
    permission: pistonentityfixer.fix
  pistonentityfixer:
    description: Plugin main command.
    permission: pistonentityfixer.fix
    aliases:
      - pef