name: PistonEntityFixer
version: ${project.version}
api-version: 1.13
main: net.pistonmaster.pistonentityfixer.PistonEntityFixer
authors: [ AlexProgrammerDE ]
description: Lists and kills entities as you wish.
permissions:
  pistonentityfixer.fix:
    description: Plugin main permission.
    default: op

commands:
  pistonentityfixer:
    description: Plugin main command.
    permission: pistonentityfixer.fix
    aliases:
      - pef